[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gymnasium_env"
version = "0.0.1"
dependencies = [
  "gymnasium==0.29.1",
  "pygame==2.6.0",
  "pre-commit",
]